name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build project
      run: make -C code
    - name: Run checks
      run: make -C code check
    - name: Run distcheck
      run: make -C code distcheck


