name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run make
      run: make -C code
    - name: make check
      run: |
        echo "Checking if the project compiles without errors..."
        $(MAKE) all
    - name: make distcheck
      run: make distcheck
