name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run make
      run: make -C code ./code/Makefile
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

